version: 0.2

phases:
  pre_build:
    commands:
      - echo "PWD=$(pwd)"
      - ls -la
      - mvn -v

 build:
  commands:
    - cd myapp
    - pwd
    - mvn clean package -DskipTests
    - ls -la target
    - docker build -t springboot-demo .

  post_build:
    commands:
      - echo "Build done"
