version: 0.2

phases:
  build:
    commands:
      - cd demo
      - mvn clean package -DskipTests
      - ls -la target
      - docker build -t springboot-demo .

 build:
  commands:
    - cd myapp
    - pwd
    - mvn clean package -DskipTests
    - ls -la target
    - docker build -t springboot-demo .

  post_build:
    commands:
      - echo "Build done"
