version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 532613442480.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started
      - mvn clean package
      - docker build -t springboot-demo .
      - docker tag springboot-demo:latest 532613442480.dkr.ecr.us-east-1.amazonaws.com/springboot-demo:latest
  post_build:
    commands:
      - echo Pushing Docker image
      - docker push 532613442480.dkr.ecr.us-east-1.amazonaws.com/springboot-demo:latest