version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "532613442480"
    AWS_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "Logging into ECR"
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 532613442480.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t springboot-demo .

  post_build:
    commands:
      - docker tag springboot-demo:latest 532613442480.dkr.ecr.us-east-1.amazonaws.com/springboot-demo:latest
      - docker push 532613442480.dkr.ecr.us-east-1.amazonaws.com/springboot-demo:latest
