version: 0.2

phases:
  pre_build:
    commands:
      - echo "At repo root:"
      - pwd
      - ls -la

  build:
    commands:
      # Build the jar inside demo WITHOUT leaving repo root
      - mvn -f demo/pom.xml clean package -DskipTests

      # Prove the jar exists
      - ls -la demo/target

      # Build docker from repo root (.)
      - docker build -t springboot-demo .

  post_build:
    commands:
      - echo "Build done"
