version: 0.2

phases:
  pre_build:
    commands:
      - echo "PWD=$(pwd)"
      - ls -la
      - mvn -v

  build:
    commands:
      - mvn clean package -DskipTests
      - echo "After mvn:"
      - ls -la
      - ls -la target || true
      - find . -maxdepth 3 -type f -name "*.jar" -print
      - docker build -t springboot-demo .

  post_build:
    commands:
      - echo "Build done"
